title: jokebot
hero_image: images/banner.png
description: jokebot description
version: 4
listed: false
copyedit: false
last_tested: "2018-05-23"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
